stages:
  - build-dc
  - build-gcp
  - deploy-dc
  - deploy-gcp

build_dc:
  stage: build-dc
  script:
    - ./build/scripts/docker-check-space.sh
    - ./build/scripts/build-dc.sh $CI_COMMIT_SHORT_SHA
    - ./build/scripts/commit-image.sh $CI_COMMIT_SHORT_SHA
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*requirement.*/'
  tags:
    - office
  artifacts:
    paths:
      - deploy/images/airflow-image

build_gcp:
  stage: build-gcp
  script:
    - ./build/scripts/docker-check-space.sh
    - ./build/scripts/build-gcp.sh $CI_COMMIT_SHORT_SHA
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*requirement.*/'
  tags:
    - runner-tag
  artifacts:
    paths:
      - deploy/images/airflow-image



deploy_loto_preprod:
  stage: deploy-dc
  script:
    - helm template -f deploy/project/Chart-project1.yaml deploy/
    - export  KUBECONFIG=~/.kube/config-project1
    - kubectl get no
   #- helm upgrade --install airflow -n lottery -f deploy/project/Chart-project1.yaml  deploy/
  when: manual
  tags:
    - office

deploy_loto_prod:
  stage: deploy-dc
  script:
    - helm template -f deploy/project/Chart-projec5.yaml deploy/
    #- export  KUBECONFIG=~/.kube/project5
    #- kubectl get no
    #- helm upgrade --install airflow -n lottery -f deploy/project/Chart-project5.yaml  deploy/
  when: manual
  tags:
    - office

deploy_lottery_qa:
  stage: deploy-gcp
  script:
    - helm template -f deploy/project/Chart-lottery-qa.yaml deploy/
    - gcloud container clusters get-credentials project3 --region europe-west1 --project project3
    - kubectl get no
    #- helm upgrade --install airflow -n default -f deploy/project/Chart-project3.yaml  deploy/
  when: manual
  tags:
    - runner-tag