kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: airflow-reader-bind
  labels:
    tier: airflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-reader-role
subjects:
  - kind: ServiceAccount
    name: airflow-webserver
    namespace: {{ .Values.namespace }}