apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.namespace }}
  name: airflow-scheduler-role-bind
  labels:
    tier: airflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-scheduler-role
subjects:
  - kind: ServiceAccount
    name: airflow-scheduler
    namespace: {{ .Values.namespace }}