apiVersion: v1
kind: Secret
metadata:
  name: airflow-metadata
  namespace: {{ .Values.namespace }}
  labels:
    tier: airflow
type: Opaque
data:
  connection: {{ .Values.database_connect  | quote }}